### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sappelhoff** [jackz314/eeglabio#12]
Hi @jackz314 could we please get a new release on pypi?

I need the fix from #11 and would rather not install the development version of this repo.

Please also note that the most recent release on pypi is missing from the GitHub releases here: https://github.com/jackz314/eeglabio/releases

Finally, I see that the pypi project only has you as a single maintainer: https://pypi.org/project/eeglabio/

Would you be willing to add someone from the MNE-Python team (for example @larsoner, if he is willing) to help making new releases?

Thanks!

**Comment by sappelhoff** [comment]
Thanks!

> I just released the latest version on pypi and GitHub

it seems like you released the old (previously missing) 0.0.2.post4 release to GitHub, which had been on PyPI for a while already.

On PyPI I know also see v0.0.3, but this is not yet on GitHub. Was there a mixup? Or is v0.0.3 simply missing from GitHub so far?

> I, if I'm not able to release, as maintainers on GitHub you should be able to release to PyPI automatically by creating a version tag 

Good to know, thanks. I am not (yet) a collaborator on this repo, so would not be able to push. Please feel free to invite me if you want to.

> I'm also willing to add people to the pypi project if it's still needed, please let me know. Thanks!

I think it'd be great if you could add @larsoner (`Eric89GXL`) and myself (`sappelhoff`).

**Comment by jackz314** [comment]
Sorry for the delay, I just released 0.0.3 on GitHub as well, I forgot to click publish earlier. I invited you to the repo, and I invited you and @larsoner to the pypi project, let me know if you didn't get the invites. Thanks!

**Comment by sappelhoff** [comment]
thanks!
