### ISSUE TITLE
BUG: All numeric types during export should be double

### ISSUE THREAD

**Issue by larsoner** [jackz314/eeglabio#8]
*Quoting https://github.com/mne-tools/mne-python/issues/11031 :*

Reading a file exported by MNE on MATLAB

```
EEG.trials

ans =

  int64

   105
```

The type is int64 instead of double. This can cause all kinds of problems (I was trying to use the number of trials to calculate a ratio, and it was always returning the wrong value for example). This might be the case as well for other fields.

**Comment by jackz314** [comment]
@arnodelorme I will cast this to double. Should all scalar fields be double (e.g. `nbchan`, `srate`, etc.)?

**Comment by arnodelorme** [comment]
Yes, all numerical fields should be double.

Arno

**Comment by jackz314** [comment]
This should be fixed in the latest code

**Comment by jackz314** [comment]
Should be fixed in [v0.0.2.post3](https://github.com/jackz314/eeglabio/releases/tag/v0.0.2.post3).
