### ISSUE TITLE
Export to EEGLAB should support single and double precision

### ISSUE THREAD

**Issue by larsoner** [jackz314/eeglabio#9]
*Quoting https://github.com/mne-tools/mne-python/issues/11015* :

Currently, exporting to EEGLAB always writes double precision floats. However, @arnodelorme mentioned in #11013, the EEGLAB default is actually single precision. Therefore, we should introduce a new parameter `precision` with two possible options `"single"` and `"double"`. I'm not sure what the default should be, probably `"double"` to be on the safe side.

This should probably be implemented in `eeglabio`. Speaking of which, I wanted to suggest to include the code in MNE-Python directly to make things easier for us. I know we discussed outsourcing this to minimize maintenance costs for us, but this is not really the case. I actually think that maintenance will be easier if we have this code in our package. WDYT?

**Comment by arnodelorme** [comment]
I think the default should be single precision (32 bits).
The max precision of EEG is considered to be 19 bits. BIOSEMI file format is 24 bits. EDF is 16 bits.
64 bit is overkill. For computation (ICA, filtering), data should be converted to double precision though.

**Comment by jackz314** [comment]
Makes sense, just pushed an update for precision support

**Comment by jackz314** [comment]
Should be fixed in [v0.0.2.post3](https://github.com/jackz314/eeglabio/releases/tag/v0.0.2.post3).
